# Generated by Django 4.1.7 on 2023-03-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
